### ISSUE TITLE
Missing currency

### ISSUE THREAD

**Issue by sylvanr** [codeforIATI/imf-exchangerates#3]
Currently available, is the USD converted rate at https://codeforiati.org/imf-exchangerates/imf_exchangerates.csv. 

There are several rows that contain no data for the currency).  
Some example rows that have this behaviour are: 
```
row 33340: 2010-10-31,1.79,,M,IMF,1C_355,Curacao & St. Maarten
row 34420: 1946-12-31,50,,M,IMF,CSH,Former Czechoslovakia
row 37741: 1967-01-31,2.22,,M,IMF,DE2,East Germany
row 43416: 1999-01-31,0.878425860857344,,M,IMF,U2,Euro area (Member States and Institutions of the Euro Area) changing composition
row 133615: 1967-01-31,0.899999999,,M,IMF,SUH,Former U.S.S.R.
row 140292: 1968-12-31,2.793299999,,M,IMF,1C_473,Yemen Arab Rep.
... 1957-01-31,0.357142857142857,,M,IMF,1C_459,"Yemen, P.D. Rep."
row 141311: 1957-01-31,0.000607692307692308,,M,IMF,YUC,Former Yugoslavia
```
Later on this goes for: CEMAC, Eastern Caribbean Currency Union, WAEMU (West African Economic and Monetary Union)

This has been the case every time I checked the output (also a week ago etc.).

**Comment by andylolz** [comment]
Right yes, I see. Looks like this is the fallback for missing country-currency lookups:
https://github.com/codeforIATI/imf-exchangerates/blob/81687e64d4f8a108e70ca8f057670c136493875e/imf-currencies.py#L100-L101

I think the way to fix it would be to add these currencies to the MISSING lookup:
https://github.com/codeforIATI/imf-exchangerates/blob/81687e64d4f8a108e70ca8f057670c136493875e/imf-currencies.py#L28-L35

However, it’s a bit tricky to figure out what the currency codes should be for these historical currencies… I suspect that might be why @markbrough has not added them.

What do you think would be best here, @sylvanr? I guess one option would be to just skip these rows on output?

**Comment by matmaxgeds** [comment]
I know WAEMU changed from CFA to ECO in 2020.....but I think the historical codes are still maintained e.g. see: https://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes

**Comment by notshi** [comment]
*May* be helpful but from the readme:
>  [the IMF's Metadata PDF document for this dataset](https://data.imf.org/api/document/download?key=62969181)

This pdf includes notes on currencies for CEMAC, Eastern Caribbean Currency Union, WAEMU (West African Economic and Monetary Union). 

[Eastern Caribbean Currency Union](https://en.wikipedia.org/wiki/Eastern_Caribbean_Currency_Union) seems to use the XCD (Eastern Caribbean dollar) via [IMF](https://www.imf.org/external/pubs/nft/op/195/index.htm#overview).

More notes via [this WAEMU wiki](https://en.wikipedia.org/wiki/Economic_Community_of_West_African_States#West_African_Economic_and_Monetary_Union) page, [this CEMAC wiki](https://en.wikipedia.org/wiki/Economic_Community_of_Central_African_States#Economic_and_Monetary_Community_of_Central_Africa) page and the variations of the [CFA franc](https://en.wikipedia.org/wiki/CFA_franc#Institutions), namely XOF (WAEMU) and XAF (CEMAC).

Looks like [Eco](https://en.wikipedia.org/wiki/Eco_(currency)) is being [delayed](https://www.cnbc.com/2020/09/29/west-africas-new-currency-could-now-be-delayed-by-five-years.html) by 3-5 years.

**Comment by andylolz** [comment]
Thanks both! Using those links I’ve tried to fill in some gaps, but I’m not really sure about them, particularly given the dates. Here’s where I got to:

| Country | Start date | End date | Country code | Currency code |
|-----|-----|-----|-----|-----|
| Curacao & St. Maarten | 2010-10-31 | 2021-05-31 | 1C_355 | ANG |
| Former Czechoslovakia | 1946-12-31 | 1992-12-31 | CSH | CSJ |
| East Germany | 1967-01-31 | 1973-12-31 | DE2 | DDM |
| Euro area (Member States and Institutions of the Euro Area) changing composition | 1999-01-31 | 2021-05-31 | U2 |  |
| Former U.S.S.R. | 1967-01-31 | 1973-12-31 | SUH | SUR |
| Yemen Arab Rep. | 1968-12-31 | 1990-04-30 | 1C_473 | YDD |
| Yemen, P.D. Rep. | 1957-01-31 | 1990-04-30 | 1C_459 | YDD |
| Former Yugoslavia | 1957-01-31 | 1992-11-30 | YUC |  |
| CEMAC | 1957-01-31 | 2021-05-31 | 5X |  |
| Eastern Caribbean Currency Union | 1957-01-31 | 2021-05-31 | 5Y |  |
| WAEMU (West African Economic and Monetary Union) | 1957-01-31 | 2021-05-31 | 7A |  |

I think I’ll give up and leave this with @markbrough!

**Comment by markbrough** [comment]
Apologies, I missed this! It would be great to fix this up. Perhaps we should adjust around these lines, to import data from a CSV file instead, which would make this much easier to maintain over time?

https://github.com/codeforIATI/imf-exchangerates/blob/f72dbb262c71275d6d7c3881ce027fbe167d034b/imf-currencies.py#L24-L36
